from .utils.comm import get_uuid
import os

INIT_CONFIG = [
    {
        "verbose_name": "sm4加密key",
        "param_name": "secret_key",
        "param_value": get_uuid(),
        "param_type": "string",
        "system": "common",
        "description": "",
    },
    {
        "verbose_name": "sm4加密模式",
        "param_name": "secret_mode",
        "param_value": "ecb",
        "param_type": "string",
        "system": "common",
        "description": "",
    },
    {
        "verbose_name": "开启同步",
        "param_name": "zabbix_is_sync",
        "param_value": os.environ.get('ZABBIX_SERVER', 0),
        "param_type": "int",
        "system": "zabbix",
        "description": "是否开启资产同步zabbix监控",
    },
    {
        "verbose_name": "zabbix地址",
        "param_name": "zabbix_url",
        "param_value": os.environ.get('ZABBIX_URL', ''),
        "param_type": "string",
        "system": "zabbix",
        "description": "例如: http://127.0.0.1/api_jsonrpc.php",
    },
    {
        "verbose_name": "zabbix-server的IP",
        "param_name": "zabbix_server",
        "param_type": "string",
        "param_value": os.environ.get('ZABBIX_SERVER', '127.0.0.1'),
        "system": "zabbix",
        "description": "例如: zabbix-server的IP地址",
    },
    {
        "verbose_name": "zabbix管理用户",
        "param_name": "zabbix_username",
        "param_type": "string",
        "param_value": os.environ.get('ZABBIX_USERNAME', 'Admin'),
        "system": "zabbix",
        "description": "",
    },
    {
        "verbose_name": "密码",
        "param_name": "zabbix_password",
        "param_type": "string",
        "param_value": os.environ.get('ZABBIX_PASSWORD', 'zabbix'),
        "system": "zabbix",
        "description": "",
    },
    {
        "verbose_name": "主机模板",
        "param_name": "zabbix_host_template",
        "param_type": "string",
        "param_value": os.environ.get('ZABBIX_DEFAULT_HOST_TEMPLATE', 'Linux by Zabbix agent'),
        "system": "zabbix",
        "description": "填写zabbix主机监控模板的名称(全英文，不是模板可见名称!)",
    },
    # 新增，需要考虑更新类如何做
    {
        "verbose_name": "服务器IPMI模板",
        "param_name": "zabbix_ipmi_template",
        "param_type": "string",
        "param_value": os.environ.get('ZABBIX_DEFAULT_HOST_TEMPLATE', "Chassis by IPMI"),
        "system": "zabbix",
        "description": "填写zabbix主机监控模板的名称(全英文，不是模板可见名称!)",
    },
    {
        "verbose_name": "network模板",
        "param_name": "zabbix_network_template",
        "param_type": "string",
        "param_value": os.environ.get('ZABBIX_DEFAULT_NETWORK_TEMPLATE', 'Generic by SNMP'),
        "system": "zabbix",
        "description": "填写zabbix网络监控模板的名称(全英文，不是模板可见名称!)",
    },
    {
        "verbose_name": "token注销时间",
        "param_name": "zabbix_interval",
        "param_type": "int",
        "param_value": os.environ.get('ZABBIX_INTERVAL', 0),
        "system": "zabbix",
        "description": "单位秒,0表示不过期",
    },
    {
        "verbose_name": "资产自更新",
        "param_name": "asset_auto_update",
        "param_type": "int",
        "param_value": 1,
        "system": "node_mg",
        "description": "单位秒,0表示不过期",
    },
    {
        "verbose_name": "更新周期",
        "param_name": "asset_task_interval",
        "param_type": "string",
        "param_value": "1d",
        "system": "node_mg",
        "description": "单位秒,0表示不过期",
    },
]
